export enum OrderStatus {
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  PROCESSING = 'PROCESSING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_PICKUP = 'PENDING_PICKUP',
  PENDING_DELIVERY = 'PENDING_DELIVERY',
  DELIVERED = 'DELIVERED',
  RECEIVED = 'RECEIVED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethods {
  WEB3 = 'WEB3',
  SEPAY = 'SEPAY',
  COD = 'COD',
}
