import GuardLayoutWrapper from '@/hocs/GuardLayoutWrapper';
import LayoutPublic from '@/views/layouts/LayoutPublic';
import PaymentPage from '@/views/pages/payment/[id]';
import { Metadata } from 'next';
import { ReactElement } from 'react';

export const metadata: Metadata = {
  title: 'Payment - FastE',
  description: 'Generated by create next app',
};

export default function Page({ params }: { params: { id: number } }) {
  return (
    <GuardLayoutWrapper
      getLayout={(page: ReactElement) => <LayoutPublic>{page}</LayoutPublic>}
      authGuard={true}
      guestGuard={false}
    >
      <PaymentPage id={params.id} />
    </GuardLayoutWrapper>
  );
}
