import ProductDetailPage from '@/views/pages/sellercenter/products/detail';
import EditProductPage from '@/views/pages/sellercenter/products/edit';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Chi tiết sản phẩm - FastE',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <ProductDetailPage />
    </>
  );
}
