import MediaLibraryPage from '@/views/pages/admin/media';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Thư viện phương tiện - FastE',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <MediaLibraryPage />
    </>
  );
}
